[package]
name = "current-thread-runtime"
version = "0.1.0"
authors = ["Alexander Polakov <plhk@sdf.org>"]
edition = "2018"

[dependencies]
tokio-executor = "0.1"
tokio-current-thread = "0.1"
tokio = "0.1"
tokio-timer = "0.2"
tokio-reactor = "0.1"
futures = "0.1"
